### ISSUE TITLE
Feature: Arbre de Nadal

### ISSUE THREAD

**Issue by JosepRamonC** [JordiMolas/Dia1.P0_JordiM#1]
Anem a fer una issue al Repo d'en Jordi

**Comment by JordiMolas** [comment]
O sigui, que tu decideixes posar-me un arbre al meu repo... :D

**Comment by JosepRamonC** [comment]
Tu em vas donar permís per accedir :p

**Comment by JosepRamonC** [comment]
Feature realitzada (Ara faltaria merge amb la main)

**Comment by JosepRamonC** [comment]
Preparat per aprovarPull Request  i fer Merge per part d'en Jordi

**Comment by JordiMolas** [comment]
Josep, no m'has creat PR ? no

**Comment by JosepRamonC** [comment]
Sí

**Comment by JordiMolas** [comment]
Mira, just ara....

**Comment by JosepRamonC** [comment]
A la part superior al Tab Pull Requests
